# Generated by Django 3.0.5 on 2020-08-15 12:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productdetail',
            name='product_image',
            field=models.FileField(upload_to='myapp/images/'),
        ),
    ]
