# Generated by Django 3.0.5 on 2020-08-15 13:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_auto_20200815_1805'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productdetail',
            name='product_image',
            field=models.ImageField(blank=True, null=True, upload_to='F:\\python\\Django\\ecomm\\media'),
        ),
    ]
